#Server Name
server: PeyangServer

#Unit of money
unit: Peyallion

#is Allow Debt
debt: false

#Language
lang: ja_JP.yml

#item (9 more)
item:
  - COAL
  - WHEAT
  - SLIME_BALL
  - IRON_NUGGET
  - IRON_INGOT
  - GOLD_NUGGET
  - GOLD_INGOT
  - GHAST_TEAR
  - DIAMOND
sign: "[ATM]"